### ISSUE TITLE
Module not found: Error: Can't resolve '@arco-themes/react-easy-email-theme/css/arco.css

### ISSUE THREAD

**Issue by dr-ramix** [zalify/easy-email-editor#133]
Hey, 
I'm trying to use this project in my react app. I've done everything step by step. But, I have problems. When I run the app there is an error wich says: 
`Module not found: Error: Can't resolve '@arco-themes/react-easy-email-theme/css/arco.css`

I deleted that part so the app runs but the functions doesn't and the style of elements is honestly unexpected.

**Comment by m-Ryan** [comment]
If you need a custom theme, you need to install. This is optional.

```
yarn add @arco-themes/react-easy-email-theme
```
---
Here is a quick start demo [https://github.com/m-Ryan/easy-email-demo](https://github.com/m-Ryan/easy-email-demo)
