### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by wagnerlduarte** [zalify/easy-email-editor#191]
When I run the project using Next.JS I get this error about `react-final-form` in `easy-email-editor`:
![image](https://user-images.githubusercontent.com/17439470/207064883-f0380331-b5c4-41b2-8ef5-686cd909382b.png)

Some way to solve it?

**Comment by wagnerlduarte** [comment]
> When I run the project using Next.JS I get this error about `react-final-form` in `easy-email-editor`: ![image](https://user-images.githubusercontent.com/17439470/207064883-f0380331-b5c4-41b2-8ef5-686cd909382b.png)
> 
> Some way to solve it?

I solved this issue using the `next-transpile-modules` following the README to install: https://www.npmjs.com/package/next-transpile-modules

My `next.config.js` file looks like this:

```
const withTM = require("next-transpile-modules")(["easy-email-editor"]);

module.exports = withTM({});
```

After that, I got the same error of this issue: https://github.com/zalify/easy-email/issues/88
But I solved with this nice comment: https://github.com/zalify/easy-email/issues/88#issuecomment-1043453584

So... I don't know yet if this error should happen 🤷‍♂️

**Comment by m-Ryan** [comment]
Please do not import them in server. ES module can not run in NodeJS.
Try 
```tsx
import dynamic from "next/dynamic";
```
