### ISSUE TITLE
 do not use legacy react-dom/server APIs.

### ISSUE THREAD

**Issue by AlessandroOliiveira** [zalify/easy-email-editor#372]
I was trying to implement Easy email on the Next Js@14, but I got this error:

Error: Internal Error: do not use legacy react-dom/server APIs. If you encountered this error, please open an issue on the Next.js repo.

Does anyone know about this?
![Captura de tela de 2023-12-15 20-33-21](https://github.com/zalify/easy-email/assets/83770093/1194fa1d-a626-4b5b-851f-8e932a072178)

**Comment by monsterooo** [comment]
As far as I know, https://react.dev/reference/react-dom/server/renderToPipeableStream should be used. I wonder if anyone has fixed this problem. @m-Ryan 

Thank you!

**Comment by ShahriarKh** [comment]
see https://github.com/vercel/next.js/discussions/58305#discussioncomment-7785006
