### ISSUE TITLE
Unable to type into hyperlink popover input

### ISSUE THREAD

**Issue by sarbjeet6706** [zalify/easy-email-editor#377]
<img width="994" alt="Screenshot 2024-01-29 at 2 00 42 PM" src="https://github.com/zalify/easy-email/assets/4946516/63c1dd7e-1d6e-493f-b923-6c33a175330a">

**Comment by m-Ryan** [comment]
Can't reproduce? Is your browser chrome?

**Comment by sarbjeet6706** [comment]
yes I am using chrome

**Comment by sarbjeet6706** [comment]
It was an issue with UI Framework. I am closing it

**Comment by sarbjeet6706** [comment]
Resolved
