### ISSUE TITLE
NPM install points to another repository

### ISSUE THREAD

**Issue by ankurparihar** [zalify/easy-email-editor#384]
`npm install --save easy-email-core`

easy-email-core is mapped to - https://github.com/m-Ryan/easy-email on npm, which is forked project and a few commit behind.

https://www.npmjs.com/package/easy-email-core

**Comment by m-Ryan** [comment]
The file mapping is indeed wrong. This repo is correct and will be modified in the next version.

**Comment by ankurparihar** [comment]
Awesome,  thank you!

**Comment by diragb** [comment]
Encountering the same issue, is there any way around it?

**Comment by m-Ryan** [comment]
Fixed
