### ISSUE TITLE
Custom block not on focus

### ISSUE THREAD

**Issue by Alessandro-rep** [zalify/easy-email-editor#386]
I have created my custom block and it works fine, but when i drag and drop it on my central editor i can't select it, it doesn't go on focus, i have to open the layer view and select my block from there, then it opens the panel on the right to modify.

What could be the problem here? I followed all the steps to create the block but i can't find nothing more to help with my problem.

/* eslint-disable react/jsx-wrap-multilines */
import React, { useCallback, useMemo, useState } from 'react';
import { Button, message, PageHeader } from 'antd';
import mjml from 'mjml-browser';

import {
  BlockAvatarWrapper,
  EmailEditor,
  EmailEditorProvider,
  IEmailTemplate,
  Stack,
} from 'easy-email-editor';
import 'easy-email-editor/lib/style.css';
import 'antd/dist/antd.css';

import templateData from './template.json'
import { useImportTemplate } from './hooks/useImportTemplate';
import { useExportTemplate } from './hooks/useExportTemplate';
import { copy } from './urils/clipboard';
import { AdvancedType, BasicType, BlockManager, JsonToMjml } from 'easy-email-core';
import { ExtensionProps, SimpleLayout, StandardLayout } from 'easy-email-extensions';
import { FormApi } from 'final-form';
import 'easy-email-editor/lib/style.css';
import 'easy-email-extensions/lib/style.css';
import '@arco-themes/react-easy-email-theme-purple/css/arco.css';
import {useWindowSize} from 'react-use'
import { CustomBlocksType } from './CustomBlocks/constants';

import './CustomBlocks';

const fontList = [
  'Arial',
  'Tahoma',
  'Verdana',
  'Times New Roman',
  'Courier New',
  'Georgia',
  'Lato',
  'Montserrat',
  '黑体',
  '仿宋',
  '楷体',
  '标楷体',
  '华文仿宋',
  '华文楷体',
  '宋体',
  '微软雅黑',
].map(item => ({ value: item, label: item }));

const categories: ExtensionProps['categories'] = [
  {
    label: 'Content',
    active: true,
    blocks: [
       
      {
        type: AdvancedType.TEXT,
      },
      {
        type: AdvancedType.IMAGE,
        payload: { attributes: { padding: '0px 0px 0px 0px' } },
      },
      {
        type: AdvancedType.DIVIDER,
      },
      {
        type: AdvancedType.SPACER,
      },
      {
        type: AdvancedType.BUTTON,
      },
      {
        type: AdvancedType.NAVBAR,
      },
      {
        type: AdvancedType.SOCIAL,
      },
      {
        type: AdvancedType.CAROUSEL,
      },
      {
        type: AdvancedType.WRAPPER,
      },
      {
        type: AdvancedType.SECTION,
      },
      {
        type: AdvancedType.COLUMN,
      },
      {
        type: AdvancedType.GROUP,
      },
      {
        type: BasicType.HERO,
      },
    ],
  },
    //Layout Colonne
  {
    label: 'Layout',
    active: true,
    displayType: 'column',
    blocks: [
      {
        title: '2 columns',
        payload: [
          ['50%', '50%'],
          ['33%', '67%'],
          ['67%', '33%'],
          ['25%', '75%'],
          ['75%', '25%'],
        ],
      },
      {
        title: '3 columns',
        payload: [
          ['33.33%', '33.33%', '33.33%'],
          ['25%', '25%', '50%'],
          ['50%', '25%', '25%'],
        ],
      },
      {
        title: '4 columns',
        payload: [
          ['25%', '25%', '25%', '25%'],
          ['20%', '30%', '30%', '20%'],
          ['30%', '30%', '20%', '20%'],
          ['20%', '20%', '30%', '30%'],
        ],
      },
    ],
  },
  {
    label: 'Custom',
    active: true,
    displayType: 'custom',
    blocks: [
      <BlockAvatarWrapper type={CustomBlocksType.BLOCCO_TEST}>
        <div
            style={{
              position: 'relative',
              border: '1px solid #ccc',
              marginBottom: 20,
              width: '80%',
              marginLeft: 'auto',
              marginRight: 'auto',
            }}
        >
          <img
              src={
                'https://easy-email-m-ryan.vercel.app/images/dd1584fb-cb60-42c9-80c7-5545e16130ca-226ba72b-ce9e-4948-ad0d-347381fb96c5.png'
              }
              style={{
                maxWidth: '100%',
              }}
          />
          <div
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                height: '100%',
                zIndex: 2,
              }}
          />
        </div>
      </BlockAvatarWrapper>,
      <BlockAvatarWrapper type={CustomBlocksType.PRODUCT_RECOMMENDATION}>
      <div
          style={{
            position: 'relative',
            border: '1px solid #ccc',
            marginBottom: 20,
            width: '80%',
            marginLeft: 'auto',
            marginRight: 'auto',
          }}
      >
        <img
            src={
              'https://easy-email-m-ryan.vercel.app/images/dd1584fb-cb60-42c9-80c7-5545e16130ca-226ba72b-ce9e-4948-ad0d-347381fb96c5.png'
            }
            style={{
              maxWidth: '100%',
            }}
        />
        <div
            style={{
              position: 'absolute',
              top: 0,
              left: 0,
              width: '100%',
              height: '100%',
              zIndex: 2,
            }}
        />
      </div>
    </BlockAvatarWrapper>
    ]}
];

const pageBlock = BlockManager.getBlockByType(BasicType.PAGE)!;

export default function Editor() {
  const [downloadFileName, setDownloadName] = useState('download.mjml');
  // const [template, setTemplate] = useState<IEmailTemplate['content']>(pageBlock.create({
  //   data: {
  //     value: {
  //       "content-background-color": '#ffffff'
  //     }
  //   }
  // }));
  const [template, setTemplate] = useState<IEmailTemplate['content']>(templateData);
  const { importTemplate } = useImportTemplate();
  const { exportTemplate } = useExportTemplate();

  const { width } = useWindowSize();

  const smallScene = width < 1400;

  const onCopyHtml = (values: IEmailTemplate) => {
    const html = mjml(JsonToMjml({
      data: values.content,
      mode: 'production',
      context: values.content
    }), {
      beautify: true,
      validationLevel: 'soft',
    }).html;

    copy(html);
    message.success('Copied to pasteboard!')
  };

  const onImportMjml = async () => {
    try {
      const [filename, data] = await importTemplate();
      setDownloadName(filename);
      setTemplate(data);
    } catch (error) {
      message.error('Invalid mjml file');
    }
  };

  const onExportMjml = (values: IEmailTemplate) => {
    exportTemplate(
      downloadFileName,
      JsonToMjml({
        data: values.content,
        mode: 'production',
        context: values.content
      }))
  };

  const onSubmit = useCallback(
    async (
      values: IEmailTemplate,
      form: FormApi<IEmailTemplate, Partial<IEmailTemplate>>
    ) => {
      console.log('values', values)

      // form.restart(newValues); replace new values form backend 
      message.success('Saved success!')
    },
    []
  );

  const initialValues: IEmailTemplate | null = useMemo(() => {
    return {
      subject: 'Welcome to Easy-email',
      subTitle: 'Nice to meet you!',
      content: template
    };
  }, [template]);

  if (!initialValues) return null;

  return (
    <div>
      <button onClick={ () => {console.log(BlockManager.getBlocks());}}>print</button>
      <EmailEditorProvider
        dashed={false}
        data={initialValues}
        height={'calc(100vh - 85px)'}
        // onUploadImage={services.common.uploadByQiniu}

        autoComplete
        fontList={fontList}
        onSubmit={onSubmit}
      >
        {({ values }, { submit }) => {
          return (
            <>
              {/* Header Pagina  con titolo a sx e bottoni a dx*/}
              <PageHeader
                title='Edit'
                  extra={
                  <Stack alignment="center">
                      <Button onClick={() => onCopyHtml(values)}>
                        Copy Html
                      </Button>
                      <Button onClick={() => onExportMjml(values)}>
                        Export Template
                      </Button>
                      <Button onClick={onImportMjml}>
                        import Template
                      </Button>
                      <Button
                        type='primary'
                        onClick={() => submit()}
                      >
                        Save
                      </Button>
                    </Stack>
                  }
              />
          {/*Editor Laterale*/}
          <StandardLayout
            compact={!smallScene}
            categories={categories}
            showSourceCode={true}
          >
            {/* Email Editor Centrale con Preview */}
            <EmailEditor />
          </StandardLayout>
            </>
          );
        }}
      </EmailEditorProvider>
    </div>
  );
}

**Comment by m-Ryan** [comment]
Can you provide a code sandbox? It's hard for me to identify the problem now.

**Comment by Alessandro-rep** [comment]
I followed the same steps as the  ProductRecomendation.
This is a sample of the CustomBlocks folder i created:

-CustomBlocks:
	-BloccoTest:
		index.tsx -> ...
			export type IBloccoTest = IBlockData<...>
			export const BloccoTest = createCustomBlock<ICustomBlock>({...})

		Panel.tsx ->  ...
			export function BloccoTestPanel(){...}

	constants.ts ->
			export enum CustomBlocksType{
				BLOCCO_TEST = ‘blocco_test’
			}
	index.tsx ->
			BlockManager.registerBlocks({
				[CustomBlocksType.BLOCCO_TEST] : BloccoTest
			})
			BlockAttributeConfigurationManager.add({
				[CustomBlocksType.BLOCCO_TEST] : BloccoTestPanel
			})


-Editor:
	const categories: ExtensionProp[‘categories’] = [ ... ,
		{ label: ‘Custom’ …
		   blocks: [
		<BlockAvatarWrapper type = {CustomBlocksType.BLOCCO_TEST}>…,
		]}
	]

**Comment by rajathawsg** [comment]
hi @Alessandro-rep, im having the same issue, looks like i have missed something, please let me know how did you resolve this?

**Comment by Alessandro-rep** [comment]
The only missing step was specifying the parameter css-class in the outher container of the custom block:

<Wrapper 
         css-class={mode === 'testing' ? getPreviewClassName(idx, data.type) : ''}
         ...
>
...
</Wrapper>
