### ISSUE TITLE
Unregister custom block 

### ISSUE THREAD

**Issue by Alessandro-rep** [zalify/easy-email-editor#392]
Hi, i am trying to adapt the Editor to work with multiple users, each with his own Custom Blocks.
I want to unregister the blocks of a user when i close the editor, so i can register the blocks of the next user or re-register the blocks but with different styles, but the BlockManager doesn't seem to have the option to remove them.
Is there a way to unregister them, or a better way to approach this situation?
Thanks and thanks for this awesome editor.

**Comment by m-Ryan** [comment]
There are currently no options for deletion. If you need to overwrite, just register again.
