### ISSUE TITLE
blocks style

### ISSUE THREAD

**Issue by Alessandro-rep** [zalify/easy-email-editor#394]
Is there a way to edit the default style of Basic/ Advanced blocks?
So that i don't have to generate custom blocks.
Thanks

**Comment by m-Ryan** [comment]
If you are referring to the attributes generated by dragging the block, then they can be changed.
![image](https://github.com/zalify/easy-email-editor/assets/20615214/596df44e-fb67-4525-9b80-a72a140e9940)

**Comment by Alessandro-rep** [comment]
Can i only edit attributes with this method?
I am trying to edit the navbar, to do that i need to change data{value{links[]}} but the payload seems to only accept attributes{}

**Comment by m-Ryan** [comment]
No, accept all properties
