### ISSUE TITLE
Template editor is breaking when working with `>` characters in liquidjs

### ISSUE THREAD

**Issue by wilau2** [zalify/easy-email-editor#395]
Write directly in a text block something like: 
```
{% if 2 > 1 %}
  test
{% endif %}
```
The template editor will save it as `&gt` instead of `>` resulting in error:
`unexpected token at "&gt; 1",`

I would expect the templating language to work. 

Workaround: 
Manually edit from source code --> json source replace the `&gt;` back to `>`

**Comment by m-Ryan** [comment]
This is expected, special characters must be treated like this, If you don't want special processing, you can use html mode

<img width="1499" alt="image" src="https://github.com/zalify/easy-email-editor/assets/20615214/aba5e1e4-f251-414d-ad40-566f56b2ec55">
