### ISSUE TITLE
Custom block edit text

### ISSUE THREAD

**Issue by Alessandro-rep** [zalify/easy-email-editor#397]
How can i get the same functionality of an Advanced Text to a custom block, where i can click on the text and edit just the words i select using the grey bar that pops out at the top of the editor?

![Schermata 2024-06-06 alle 09 24 01](https://github.com/zalify/easy-email-editor/assets/126822203/a6ed0a85-d516-4e1b-a028-ac71fbbd256f)

I have a simple block with this mjml code: 
<mj-section padding="0px" text-align="left" ><mj-column ><mj-text padding="0 0 0 0" align="left" color="#151515" font-family="Open Sans, sans-serif" font-size="16px" line-height="24px" font-weight="500" >DESCRIPTION, description.</mj-text></mj-column></mj-section>

It has the same structure of a basic text block, but i can't edit the text directly by selecting it on the editor, is there a way to enable this option?

**Comment by Alessandro-rep** [comment]
this is my custom block:

![Schermata 2024-06-06 alle 09 27 09](https://github.com/zalify/easy-email-editor/assets/126822203/9ff34385-dec4-4dcd-97e4-6134060031d9)

**Comment by m-Ryan** [comment]
https://github.com/zalify/easy-email-editor/blob/master/demo/src/pages/Editor/components/CustomBlocks/ProductRecommendation/index.tsx#L109-L113
check this
