### ISSUE TITLE
Login Page is not responsive!

### ISSUE THREAD

**Issue by yogirajbshinde21** [zalify/easy-email-editor#402]
The Login content on the login page is not responsive, Can I handle it to make it responsive ?
Also, I would like to improve it's design as well.
@ghyghoo8 @willopez @browniefed @wilau2 @alexmateos 
![Screenshot 2024-06-22 222905](https://github.com/zalify/easy-email-editor/assets/84953719/70cbef12-0b60-488a-a6dc-3a356ceaa0c8)

**Comment by m-Ryan** [comment]
Thank you, but no need, because this is just a demo website
