### ISSUE TITLE
Can we cache the JsonToMjml outout?

### ISSUE THREAD

**Issue by mikicho** [zalify/easy-email-editor#406]
First, thanks for this great lib!

I want to use this package in production to render emails before sending them. Should I cache the `JsonToMjml` output and render the HTML with the dynamic data? 

According to the [EmailFlow graph](https://github.com/zalify/easy-email-editor/blob/master/Email-flow.md), `JsonToMjml` should repeatedly run for the same JSON with different `dataSource`. Can the `dataSource` produce different mjml? If the answer is yes, why we use template engine for condition and iteration instead of do this in the code?
I use custom data, conditions, and iterations in my templates.

**Comment by mikicho** [comment]
Oh! this is great!
Know I finally understand why you wrap the `if` expressions in the `Condition` with `Raw` block.
Thanks!!

**Comment by mikicho** [comment]
@m-Ryan I wonder why the `JsonToMjml` gets the `dataSource`. It's sort of a pitfall that I fell into earlier.

**Comment by m-Ryan** [comment]
https://docs.easyemail.pro/docs/advanced/custom-block#testingproduction-mode

This is the documentation for the pro version of custom block. Most of the concepts are the same. Because custom blocks sometimes need to be combined with dynamic data in edit mode to generate previews
