### ISSUE TITLE
HTML Mode if there are errors in html the Editor Crash

### ISSUE THREAD

**Issue by Piero87** [zalify/easy-email-editor#414]
If I use the HTML Mode inside a text element:

![Screenshot 2024-09-18 alle 11 11 57](https://github.com/user-attachments/assets/445da243-1a2a-4762-80b1-f58565ad69d4)

And I add an error inside html:

![Screenshot 2024-09-18 alle 11 17 08](https://github.com/user-attachments/assets/db7610a5-2492-4e23-aea2-edb6ca9b013d)

If I use the save button the error crash  with this error for example:

`The above error occurred in the <td<> component`

In this way I lose all the work done in the editor, I see that editor looks the same of [MJML editor](https://mjml.io/try-it-live), and here if I do the same error the preview give me the error message and don't crash:

![Screenshot 2024-09-18 alle 11 18 03](https://github.com/user-attachments/assets/b5088858-38cd-4aae-9e3b-1618cce12241)

can anything be done to avoid losing all the work and catch the error just like the mjml editor does?

**Comment by m-Ryan** [comment]
1. HTML mode is not suitable for all users. 
2. My suggestion is to use automatic saving in local storage to restore in case of crash.
