### ISSUE TITLE
Global setting 

### ISSUE THREAD

**Issue by Idaryss** [zalify/easy-email-editor#418]
Hello, first of all thank you for the superb email editor. 
I just one feature but not sure from where I should start to dev it. Some insight will be helpful.
I would like to have some other global setting. Exactly like the demo where on theme setting I can update font color I would like to have same kind for button background color and h1 for example. 
Can you please let me know some step that I can do? 

I see this below code  I think it's around here. 
https://github.com/zalify/easy-email-editor/blob/d0d65382c0e0cc11185db65f3829b78231153378/packages/easy-email-extensions/src/AttributePanel/components/UI/HtmlEditor.tsx

Thanks a lot for your help  @m-Ryan

**Comment by m-Ryan** [comment]
Setting the button color globally is not supported now.

**Comment by Idaryss** [comment]
Yes I know it's not supported but I just want to dev it in my local project . Just want to know where I should make the change I have cloned the free version and would like to dev global attribute for some stuff like H1 etc... just need to know where I should put this logici would really appreciate some insight thanks

**Comment by m-Ryan** [comment]
https://github.com/zalify/easy-email-editor/blob/master/packages/easy-email-core/src/blocks/standard/Page/index.tsx
check this

**Comment by Idaryss** [comment]
Awesome thanks you gave me a good starting point !

**Comment by Idaryss** [comment]
Again thank you My global for buttons its working using the mj-attributes logics in the page.tsx. 
I have added the globalStyle object directly to the pageData. 

If I want to not go through the `mj-attributes` (what i am currently doing) and directly assign as attributes to the mjml tags the background-color for exemple I need to go through directly the button.tsx ?and to pass the data style  `<BasicBlock>` ?Or do you see another solution ? 

If its working fine on my hands I will maybe submit a PR with this feature no ?

**Comment by Idaryss** [comment]
Hello @m-Ryan thanks a lot for your help with the files it helped doing the functionality. 
I am doing a merge from lodash with default attributes global attributes and data.atrributes. 

It's working pretty great. 

But the only left thing is that when the block is dragged the defaultAttribute is shown ( as it win the merge) but the fields in attributePannel stay empty. 

It's the only functionality left for my global attributes and I would really appreciate any help on setting up the value of the attribute panel like background color and padding for exemple if defined in defialtData of the block definition. 

I am not spreading the defaultAttribute into the data.attributes as I don't want them to be shown in my data.atrivutes to not impact the merge lodash priority

Hope you can help on this last request from my part :D
