### ISSUE TITLE
Is there a way to adjust the width of each column in a table?

### ISSUE THREAD

**Issue by hasgardee** [zalify/easy-email-editor#419]
<img width="1184" alt="Screenshot 2024-10-18 at 10 42 59 PM" src="https://github.com/user-attachments/assets/40938951-7fb1-485c-b7d7-2ae460fdd108">

Is there a way to adjust the width of each column in a table?

**Comment by m-Ryan** [comment]
Don't support setting separate widths for table colums.

**Comment by dipak-tech-aher** [comment]
@hasgardee  how did you added the table columns
